// <auto-generated />
namespace Expense_Tracker.Migrations.DataMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitialData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialData));
        
        string IMigrationMetadata.Id
        {
            get { return "202112020741486_InitialData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
